"""
AuditAI — Streamlit UI for clinical audit reports.

Workflow:
1. User uploads CSV/XLSX of audit data
2. App auto-detects boolean-like columns (yes/no, true/false, 1/0)
3. Computes per-component and overall compliance
4. Calls Claude to detect audit topic + generate tailored recommendations
   (falls back to generic hardcoded recs if API key missing)
5. Exports an NHS-styled PDF with the topic, metrics, and AI recommendations
"""

import os
import sys

# Allow imports from the same /app folder when running via `streamlit run`
sys.path.append(os.path.dirname(__file__))

import streamlit as st
import pandas as pd

from report_utils import build_pdf
from llm import generate_audit_insights, set_api_key


# --- Streamlit Cloud secrets bridge ---
# Locally, llm.py reads ANTHROPIC_API_KEY from .env automatically. On
# Streamlit Cloud, secrets live in st.secrets — we forward them here so
# llm.py works in both environments without depending on streamlit at
# import time.
try:
    if "ANTHROPIC_API_KEY" in st.secrets:
        set_api_key(st.secrets["ANTHROPIC_API_KEY"])
except Exception:
    # st.secrets raises if no secrets file present — fine, fall through to .env
    pass


st.set_page_config(page_title="AuditAI", layout="wide")
st.title("AuditAI — Clinical Audit & QI")
st.caption(
    "Upload your audit dataset. Compliance is computed automatically; "
    "tailored recommendations are generated by Claude."
)


# ------------------------------------------------------------------------
# Boolean detection helpers
# ------------------------------------------------------------------------
TRUE_SET = {"yes", "true", "1", "y", "t"}
FALSE_SET = {"no", "false", "0", "n", "f", ""}

# Columns that are obviously identifiers, not audit components
IDENTIFIER_HINTS = {"patient_id", "id", "mrn", "nhs_number", "hospital_number"}


def to_bool_series(s: pd.Series) -> pd.Series:
    """Map common yes/no/true/false/1/0 to 1.0/0.0. Unknowns become NaN."""
    x = s.astype(str).str.strip().str.lower()
    out = pd.Series(index=s.index, dtype="float")
    out = out.mask(x.isin(TRUE_SET), 1.0)
    out = out.mask(x.isin(FALSE_SET), 0.0)
    return out


def find_boolean_columns(df: pd.DataFrame) -> list[str]:
    """Return columns that look boolean-like, excluding obvious identifiers."""
    bool_cols = []
    for col in df.columns:
        if col.lower().strip() in IDENTIFIER_HINTS:
            continue
        mapped = to_bool_series(df[col])
        non_null = mapped.notna().sum()
        if non_null > 0 and (non_null / len(df) >= 0.5):
            bool_cols.append(col)
    return bool_cols


def humanise_column_name(col: str) -> str:
    """Turn 'vte_done' into 'VTE assessment performed'-style readable text."""
    # Common audit-domain abbreviations that should stay uppercase
    UPPERCASE_TOKENS = {"vte", "dvt", "pe", "crp", "ecg", "wcc", "iv", "po",
                        "im", "uti", "stat", "prn", "ct", "mri", "ed", "nhs"}
    parts = col.replace("-", "_").split("_")
    out = []
    for p in parts:
        if p.lower() in UPPERCASE_TOKENS:
            out.append(p.upper())
        else:
            out.append(p.capitalize())
    return " ".join(out)


def compute_component_compliance(df: pd.DataFrame, cols: list[str]) -> dict[str, float]:
    """Return % True among non-null values for each column."""
    agg = {}
    for col in cols:
        s = to_bool_series(df[col])
        valid = s.notna()
        agg[col] = float((s[valid] == 1.0).mean()) if valid.any() else float("nan")
    return agg


def compute_overall(df: pd.DataFrame, bool_cols: list[str]) -> tuple[float, list[str]]:
    """
    Compute overall compliance.

    If a 'compliant' column exists, use it directly (it's a per-row summary).
    Otherwise compute as AND across all detected components.

    Returns
    -------
    pct : float
        Overall compliance fraction (0–1).
    components_for_breakdown : list[str]
        The columns to show in the per-component breakdown — excludes
        'compliant' when it's used as the overall metric (avoids double-counting).
    """
    lower_cols = {c.lower(): c for c in bool_cols}

    if "compliant" in lower_cols:
        col = lower_cols["compliant"]
        s = to_bool_series(df[col])
        valid = s.notna()
        pct = float((s[valid] == 1.0).mean()) if valid.any() else 0.0
        # Exclude 'compliant' from the per-component breakdown to avoid
        # double-counting — it's a summary of the others, not an audit item.
        breakdown_cols = [c for c in bool_cols if c.lower() != "compliant"]
        return pct, breakdown_cols

    # Fallback: AND across all detected boolean columns
    if not bool_cols:
        return 0.0, []

    mask = pd.Series([True] * len(df))
    for col in bool_cols:
        s = to_bool_series(df[col])
        mask &= s.fillna(1.0) == 1.0
    return float(mask.mean()), bool_cols


# ------------------------------------------------------------------------
# UI
# ------------------------------------------------------------------------
st.subheader("Step 1 — Upload data")
uploaded_file = st.file_uploader("Upload a CSV or Excel file", type=["csv", "xlsx"])

df = None
if uploaded_file is not None:
    df = (
        pd.read_csv(uploaded_file)
        if uploaded_file.name.endswith(".csv")
        else pd.read_excel(uploaded_file)
    )

if df is not None:
    st.success(f"File uploaded: {uploaded_file.name}")

    with st.expander("Data preview", expanded=True):
        st.dataframe(df.head(20), use_container_width=True)
        st.caption(f"Rows = {df.shape[0]} | Columns = {df.shape[1]}")

    bool_cols = find_boolean_columns(df)
    if not bool_cols:
        st.error(
            "Couldn't find any boolean-like columns (Yes/No, True/False, 1/0). "
            "Add a column like 'compliant' to your dataset."
        )
        st.stop()

    # Compliance computations
    component_compliance = compute_component_compliance(df, bool_cols)
    overall_pct, breakdown_cols = compute_overall(df, bool_cols)

    st.subheader("Step 2 — Compliance summary")

    # KPI row
    k1, k2 = st.columns([1, 2])
    with k1:
        st.metric("Overall compliance", f"{overall_pct * 100:.1f}%")
    with k2:
        st.progress(overall_pct)

    # Per-component breakdown (excludes 'compliant' when used as overall)
    st.write("**Per-component compliance**")
    breakdown_df = pd.DataFrame(
        {
            "Component": [humanise_column_name(c) for c in breakdown_cols],
            "Compliance": [f"{component_compliance[c] * 100:.1f}%" for c in breakdown_cols],
        }
    )
    st.dataframe(breakdown_df, use_container_width=True, hide_index=True)

    # ------------------------------------------------------------------------
    # AI insights (topic + recommendations)
    # ------------------------------------------------------------------------
    st.subheader("Step 3 — AI insights")

    with st.spinner("Asking Claude to analyse your audit…"):
        topic, recommendations, source = generate_audit_insights(
            component_compliance={c: component_compliance[c] for c in breakdown_cols},
            overall=overall_pct,
            n_records=len(df),
            column_names=list(df.columns),
        )

    badge = "✨ Generated by Claude" if source == "claude" else "⚠️ Fallback (API unavailable)"
    st.info(f"**Detected audit topic:** {topic}  \n*{badge}*")

    st.write("**Recommendations**")
    for r in recommendations:
        st.write(f"- {r}")

    # ------------------------------------------------------------------------
    # Export PDF
    # ------------------------------------------------------------------------
    st.subheader("Step 4 — Export PDF report")

    report_title = st.text_input(
        "Report title",
        value=f"{topic} — Audit Report",
    )

    left, right = st.columns(2)
    with left:
        author_name = st.text_input("Your name", value="")
    with right:
        author_grade = st.text_input("Grade / role", value="")

    if st.button("Build PDF"):
        os.makedirs("reports", exist_ok=True)
        pdf_path = "reports/audit_report.pdf"

        # Aggregate dict: 'overall' + humanised component names
        agg_dict = {"overall": overall_pct}
        for c in breakdown_cols:
            agg_dict[humanise_column_name(c)] = component_compliance[c]

        used_logo = build_pdf(
            output_path=pdf_path,
            title=report_title,
            agg_dict=agg_dict,
            n_records=len(df),
            recommendations=recommendations,
            author_name=author_name,
            author_grade=author_grade,
            logo_path=None,
            topic=topic,
            ai_source=source,
        )

        st.caption(f"Logo source: {used_logo}")

        with open(pdf_path, "rb") as f:
            st.download_button(
                "Download PDF",
                data=f.read(),
                file_name="audit_report.pdf",
                mime="application/pdf",
            )